### ISSUE TITLE
@available no longer allowed in LocationPickerViewController

### ISSUE THREAD

**Issue by Oggerschummer** [almassapargali/LocationPicker#79]
With the latest xCode / iOS beta this

  ```
  @available(iOS 13.0, *)
    public lazy var searchTextFieldColor: UIColor = .clear
```

causes a compile error:  _Stored properties cannot be marked potentially unavailable with '@available'_
in LocationPickerViewController.

**Comment by Oggerschummer** [comment]
With latest Xcode and iOS 16 this no longer compiles. Could we please remove it ?

**Comment by Oggerschummer** [comment]
Solved by latest pull request merge

**Comment by kalmicka** [comment]
Did you guys bum up the SPM version to something higher than 1.4.3? When I pull the SPM package I still see the error even having reset package cache. Any idea on what to do?

**Comment by weakfl** [comment]
Switch to master branch. Unfortunately I don't have time to publish new releases tbh.
SPM wouldn't be a problem, but I don't use cocoapods anymore and a proper release would require updates to both.

**Comment by RajChanchal** [comment]
master branch doesn't solve the issue as well.

**Comment by Fayis2021** [comment]
@RajChanchal  Are you able to solve the issue?

**Comment by Fayis2021** [comment]
> Switch to master branch. Unfortunately I don't have time to publish new releases tbh. SPM wouldn't be a problem, but I don't use cocoapods anymore and a proper release would require updates to both.

@weakfl the error still exist . am using  Xcode 15.3  , any help?
